server:
  port: 80
spring:
#  h2:
#    console:
#      enabled: true
#      settings:
#        trace: true
#        web-allow-others: true
#      path: /h2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://192.168.121.131:3306/testdb?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
#    url: jdbc:h2:file:~/.h2/MYTESTDB;AUTO_SERVER=TRUE;MODE=Oracle;schema=andy;
    username: andy
    password: zaq12wsx
    name: testdb
# 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: 192.168.121.131
    port: 6379
    password: asdf1234
    timeout: 10
    jedis:
      pool:
        max-active: 1000
        max-wait: 1
        max-idle: 10
        min-idle: 2
        
            
#  freemarker:
#    allow-session-override: true
#    cache: true
#    charset: UTF-8
#    content-type: text/html
#    suffix: .ftl  
#    checkTemplateLocation: false
  
  thymeleaf:
    cache: false 
    servlet:
      content-type: text/html  
    enabled: true 
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
      
  dao:
    exceptiontranslation:
      enabled: true
#  security:
#    user:
#      name: andy
#      password: testpassword 
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
              
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp  
management:
  endpoints:
    web:
      exposure:
        include:  '*'
        exclude:  env,beans                  
#mybatis:
#  config-location: classpath:mybatis-configuration.xml
#  mapperLocations: classpath:com/msww/ms/*/mapper/*.xml
        
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
        